[General]
ipv6=false

[Rule]
RULE-SET,https://raw.githubusercontent.com/yueker/rules/refs/heads/main/rules/ai.yaml,AI
RULE-SET,https://raw.githubusercontent.com/yueker/rules/refs/heads/main/rules/proxy.yaml,Proxy
RULE-SET,https://raw.githubusercontent.com/yueker/rules/refs/heads/main/rules/direct.yaml,DIRECT
RULE-SET,https://raw.githubusercontent.com/yueker/rules/refs/heads/main/rules/microsoft.yaml,Microsoft
RULE-SET,https://raw.githubusercontent.com/yueker/rules/refs/heads/main/rules/telegram.yaml,Telegram
RULE-SET,https://raw.githubusercontent.com/yueker/rules/refs/heads/main/rules/reject.yaml,REJECT
RULE-SET,https://raw.githubusercontent.com/yueker/rules/refs/heads/main/rules/apple.yaml,Apple
RULE-SET,https://raw.githubusercontent.com/yueker/rules/refs/heads/main/rules/streaming.yaml,流媒体
FINAL,Proxy