[general]
ipv6 = false

[filter_remote]
https://raw.githubusercontent.com/yueker/rules/refs/heads/main/rules/ai.yaml, tag=ai
https://raw.githubusercontent.com/yueker/rules/refs/heads/main/rules/proxy.yaml, tag=proxy
https://raw.githubusercontent.com/yueker/rules/refs/heads/main/rules/direct.yaml, tag=direct
https://raw.githubusercontent.com/yueker/rules/refs/heads/main/rules/microsoft.yaml, tag=microsoft
https://raw.githubusercontent.com/yueker/rules/refs/heads/main/rules/telegram.yaml, tag=telegram
https://raw.githubusercontent.com/yueker/rules/refs/heads/main/rules/reject.yaml, tag=reject
https://raw.githubusercontent.com/yueker/rules/refs/heads/main/rules/apple.yaml, tag=apple
https://raw.githubusercontent.com/yueker/rules/refs/heads/main/rules/streaming.yaml, tag=streaming